//---------------------------------------------------------------------------------
// 							TRUMPGBA
//			       A stupid program by TENOR-Z
//                          09/24/2023
//---------------------------------------------------------------------------------
#include "gba_video.h"                //Grab the video header
#include "gba_systemcalls.h"          //System calls needed to render the image
#include "gba_input.h"                       //Get the system input
#include "gba_interrupt.h"
#include "pcx.h"						//Grab the image header generated by MAKE
#include "fade.h"                        //And the fade in effect for the start

#include <stdlib.h>

//---------------------------------------------------------------------------------
// header for binary data generated by bin2o macro in makefile
//---------------------------------------------------------------------------------
#include "trump_pcx.h"

//---------------------------------------------------------------------------------
// Create a buffer for the color palette
//---------------------------------------------------------------------------------
u16 PaletteBuffer[256];

unsigned int frame;

//---------------------------------------------------------------------------------
// Constantly scan for key input (button input)
//---------------------------------------------------------------------------------
void VblankInterrupt()
//---------------------------------------------------------------------------------
{
	frame += 1;
	scanKeys();
}


int main(void)
//---------------------------------------------------------------------------------
{
	// Set up the interrupt handlers
	irqInit();

	irqSet( IRQ_VBLANK, VblankInterrupt);


	// Enable Vblank Interrupt to allow VblankIntrWait
	irqEnable(IRQ_VBLANK);

	// Allow Interrupts
	REG_IME = 1;
	printf("\x1b[2J");					//Debug messages that were used during development

	printf("\x1b[10;10TY!");
	sleep(50000);							//This does not run


	SetMode( MODE_4 | BG2_ON );		// screen mode & background to display

	DecodePCX(trump_pcx, (u16*)VRAM , PaletteBuffer);			//Load the image and fill it using the palette we loaded

	FadeToPalette( PaletteBuffer, 60);											//And perform the fade in

	while (1)																	//Loop indefinetly.
	{
		VBlankIntrWait();
	}
}


